// alerts and sweeps constants.js
/**
 * @module Alerts and sweeps constants
 * @requires keyMirror
 */

const keyMirror = require('keymirror');

/**
 * @const TimelineConstants
 */
module.exports = keyMirror({

	REQUEST_SWEEPS_DETAILS: null,
	REQUEST_SWEEPS_DETAILS_SUCCESS: null,
	REQUEST_ALERTS_DETAILS: null,
	REQUEST_ALERTS_DETAILS_SUCCESS: null,
	REQUEST_PROJECTION_ALERTS_DETAILS: null,
	REQUEST_PROJECTION_ALERTS_DETAILS_SUCCESS: null,
	HIDE_HEADER_COMPONENT: null,
	REQUEST_TARGET_MONEY: null,
	REQUEST_SWEEP_THRESHOLD_MONEY: null,
	SET_IN_MY_ACCOUNT: null,
	SET_OUT_MY_ACCOUNT: null,
	SET_ALERT_ACCOUNT: null,
	SET_ALERT_LESS_MORE_VALUE: null,
	ALERT_TARGET_MONEY: null,
	REQUEST_SWEEP_TARGET_MONEY: null,
	RESET_POPUP: null,
	PROJECTION_ALERT_TARGET_MONEY: null,
	SET_PROJECTION_ALERT_ACCOUNT: null,
	ALERT_SWEEPS_ACCOUNT_DETAILS: null,
	ALERT_SWEEPS_ACCOUNT_DETAILS_ERROR: null,
	ALERTS_SWEEPS_FAILURE: null,
	ALERT_SWEEP_PROJECTION_LIST_FAILURE: null,
	ALERTS_LIST_FAILURE: null,
	SWEEPS_LIST_FAILURE: null,
	PROJECTIONS_LIST_FAILURE: null,
	SET_COMP_NAME: null,
	RESET_FLAG: null,
});
