/**
 * @module FinancialStoriesConstants
 * @requires keyMirror
 */

const keyMirror = require('keymirror');

/**
 * @const FinancialStoriesConstants
 */
const FinancialStoriesConstants = keyMirror({
	ACCOUNTS_LIST: null,
	ACCOUNTS_LIST_SUCCESS: null,
	ACCOUNT_DETAILS: null,
	ACCOUNT_DETAILS_SUCCESS: null,
	FINANCIAL_STORIES_TILE:null,
	REQUEST_TAGS_LIST: null,
	REQUEST_TAGS_LIST_SUCCESS: null,
	CREATE_NEW_TAG:null,
	CREATE_NEW_TAG_SUCCESS:null,
	DELETE_TAG_REQUEST:null,
    DELETE_TAG_REQUEST_SUCCESS:null,
	ASSIGN_TAG_REQUEST:null,
    ASSIGN_TAG_REQUEST_SUCCESS:null,
	UPDATE_TAG_REQUEST:null,
	UPDATE_TAG_REQUEST_SUCCESS:null,
	CREATE_UPDATE_NEW_TAG_ERROR:null,
	SET_ACCOUNT_HELP:null,

	TRANSACTION_LIST:null,
	TRANSACTION_HISTORY_PAGE_LIST:null,
	TRANSACTION_HISTORY_SORT_LIST:null,
	TRANSACTION_LIST_SUCCESS:null,
	TRANSACTION_HISTORY_LIST_ERROR:null,
	TAB_SELECT:null,
	TRANSACTION_SEARCH_LIST:null,
	TRANSACTION_SEARCH_TEXT: null,
	TRANSACTION_SEARCH_TEXT_SUCCESS:null,
	TRANSACTION_DATE_RANGE_LIST:null,
	TRANSACTION_DATE_RANGE_LIST_SUCCESS:null,
	RESET_TRANSACTION_SEARCH_TEXT:null,

	FINANCIAL_STORIES_CONNECTION_MICROTRANSACTION:null,
	FINANCIAL_STORIES_CONNECTION_CASHPOINT:null,
	FINANCIAL_STORIES_CONNECTION_INSANDOUTS:null,
	FINANCIAL_STORIES_CONNECTION_PROJECTION:null,
	FINANCIAL_STORIES_CONNECTION_MICROTRANSACTION_SUCCESS:null,
	FINANCIAL_STORIES_CONNECTION_CASHPOINT_SUCCESS:null,
	FINANCIAL_STORIES_CONNECTION_INSANDOUTS_SUCCESS:null,
	FINANCIAL_STORIES_CONNECTION_PROJECTION_SUCCESS:null,
	FINANCIAL_STORIES_TRANSACTION_TILE_ERROR:null,
	FINANCIAL_STORIES_ACCOUNT_DETAILS_ERROR:null,
	FINANCIAL_STORIES_CONNECTION:null,
	FINANCIAL_STORIES_CONNECTION_SUCCESS:null,
	microTransactions:null,
	cashpoint:null,
	insAndOuts:null,
	projection:null,
	MICRO_TRANSACTION_REQUEST : null,
	CASHPOINT_REQUEST : null,
	IN_OUT_REQUEST : null,
	MICRO_TRANSACTION_REQUEST_SUCCESS : null,
	CASHPOINT_REQUEST_SUCCESS : null,
	IN_OUT_REQUEST_SUCCESS : null,
	FINANCIAL_STORIES_UPDATE_TILE_CLICK: null,
	FINANCIAL_STORIES_UPDATE_TAG_ASSIGN: null,
	PROJECTION_TOUR_DONE_SUCESS:null,
	PROJECTION_SETTING_CLICKED : null,

	MATCHALL_FOR_DROPDOWN_SUCCESS:null,
});

module.exports = FinancialStoriesConstants;
