/**
 * @module SessionConstants
 * @requires keyMirror
 */

const keyMirror = require('keymirror');

/**
 * @const SessionConstants
 */
module.exports = keyMirror({

	REQUEST_AUTHENTICATION_UPDATE: null,

	REQUEST_ACCESS_CHALLENGE_CREATE: null,
	REQUEST_ACCESS_CHALLENGE_CREATE_SUCCESS: null,
	REQUEST_ACCESS_CHALLENGE_CREATE_ERROR: null,

	REQUEST_ACCESS_CHALLENGE_MISSING_DETAILS_ERROR: null,

	REQUEST_ACCESS_CHALLENGE_RESET: null,

	REQUEST_ACCESS_TOKEN_CREATE: null,
	REQUEST_ACCESS_TOKEN_CREATE_SUCCESS: null,
	REQUEST_ACCESS_TOKEN_CREATE_ERROR: null,
	REQUEST_ACCESS_TOKEN_MULTIPLE_ATTEMPTS_ERROR: null,

	REQUEST_ACCESS_TOKEN_RESET: null,

	REQUEST_OTP_AUTHENTICATION: null,
	REQUEST_OTP_ERROR: null,
	REQUEST_OTP_SUCCESS: null,
	REQUEST_OTP_AUTHENTICATION_RESET: null,
	REQUEST_CURRENT_USER_PHONE_NUMBER: null,
	REQUEST_CURRENT_USER_PHONE_NUMBER_SUCCESS: null,

	LOG_USER_IN: null,
	REQUEST_PUBLIC_KEY: null,
	REQUEST_PUBLIC_KEY_SUCCESS: null,

	REQUEST_BANK_ID: null,
	UPDATE_BANK_ID: null,

	GET_CURRENT_USER: null,

	PREPARE_STEPUP_AUTHENTICATION: null,
	REQUEST_STEPUP_AUTHENTICATION: null,
	REQUEST_STEPUP_AUTHENTICATION_CALLBACK: null,

	REQUEST_FIND_DETAILS_CHALLENGE_CREATE: null,

});
