// StringConstants.js
/**
 * @module StringConstants
 * 
 */

const StringConstants = {
    inputName:'inputName',
    EmptyString:'',
    toList:'toList',
    fromList:'fromList',
    From:'From',
    To:'To',
    KP:'KP',
    RP:'RP',
    CNFRM:'CNFRM',
    amt:'amt',
    when:'when',
    groupFrom_:'groupFrom_',
    credit_card:'credit_card',
    savings:'savings',
    Nooftimes:'Nooftimes',
    Pickadate:'Pickadate',
    setSelOften:'setSelOften',
    isRepeat:'isRepeat',
    stop:'stop',
    dtStart:'dtStart',
    end:'end',
    whenicancel:'whenicancel',
    dtWhen:'dtWhen',
    reference:'reference',
    Today:'Today',
    Days:'Days',
    current:'current',
    available:'available',
    tot:'tot',
    chooseDate:'Choose a date',
    Tomorrow:'Tomorrow',
    mpWhen:'when',
    mpAmount:'amount',
    mpFrom:'from',
    mpTo:'to',
    mpEdit:'edit',
    DDPayment:'DD',
    SOPayment:'SO',
    whenCancelText:'When I Cancel',
    singlePayment:'SinglePayment',
    stopitwhenText:'stopitwhenText',
    oftenText:'oftenText',
    SOText:'Standing order',
    DDText:'Direct debit',
    noOfTimesLimit:300,
    active:'active',
    weekly:'weekly',
    singlePayType:'Single payment',
    DirectDebit:'Direct debit',
    all:'all',
    payment:'Payment',
    transfer:'Transfer',
    ddText:'dd',
    oneMonthly:'1 monthly',
    DELETE_PAYEE:'DELETE_PAYEE',
    DELETE_PAYMENT:'DELETE_PAYMENT',
    EDIT_PARTIAL:'EDIT_PARTIAL',
    unallocated:'unallocated',
    weeklyUpper:'WEEKLY',
    monthly:'monthly',
    transferUpper:'TRANSFER',
    paymentUpper:'PAYMENT',
    chooseValue:'ChooseaValue',
    Type:'type',
    currencySymbol:'£',
    maxRow:200,
    referenceMaxLength:18,
};

module.exports = StringConstants;
