#!/bin/bash

# Commits content/config submodule, then stages and commits that commit to web-app

args=$@

# Commit config
cd config/settings && \
	git add . && \
	git commit -m "$args"

# Commit web app
cd ../../ && \
	git add ./config && \
	git commit -m "$args"
