#!/bin/bash

# Similar to commit, but uses a helper method for each commit that genereates a commit message based on the passed in
# argument, and the current branch name, for each repos.  A branch name like 'feature/ABC-123' will generate 'ABC-123: ${msg}',
# msg being the value of the original argument './scripts/commit-feature msg'

function feature_based_commit() {
  args=$@
  msg="$(git rev-parse --abbrev-ref HEAD | cut -f2 -d/): ${args}"
  git commit -m "$msg"
}

# Commit config
cd config/settings && \
	git add . && \
	feature_based_commit $@

# Commit web app
cd ../../ && \
	git add ./config && \
	feature_based_commit $@
