export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SERVICE_ERROR = 'SERVICE_ERROR';

export const TRANSFER_MONEY = 'TRANSFER_MONEY';
export const BACK_FUND_TRANFER = 'BACK_FUND_TRANFER';
export const THANK_YOU_TRANSFER = 'THANK_YOU_TRANSFER';

export const TEXT_TO_SPEECH_REQUEST = 'TEXT_TO_SPEECH_REQUEST';
export const TEXT_TO_SPEECH_SUCCESS = 'TEXT_TO_SPEECH_SUCCESS';

export const GET_TEMPRATURE_REQUEST = 'GET_TEMPRATURE_REQUEST';
export const GET_TEMPRATURE_SUCCESS = 'GET_TEMPRATURE_SUCCESS';

export const GET_ALL_TEMPRATURE_REQUEST = 'GET_ALL_TEMPRATURE_REQUEST';
export const GET_ALL_TEMPRATURE_SUCCESS = 'GET_ALL_TEMPRATURE_SUCCESS';